# Generated by Django 4.2.3 on 2023-07-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blogmodel_options_alter_blogmodel_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(to='main.tagmodel'),
        ),
    ]
